### ISSUE TITLE
When I trained this code, he happened this error. 

### ISSUE THREAD

**Issue by song201216** [wds1998/Edge-LBAM#2]
When I trained this code, he happened this error. However, I don't know how to solve it
Traceback (most recent call last):
  File "E:/code/Edge-LBAM-main/train.py", line 59, in <module>
    config = Config("config.yml")
  File "E:\code\Edge-LBAM-main\MECNet\config.py", line 6, in __init__
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'
Cuda is available!

**Comment by wds1998** [comment]
> When I trained this code, he happened this error. However, I don't know how to solve it
> Traceback (most recent call last):
> File "E:/code/Edge-LBAM-main/train.py", line 59, in
> config = Config("config.yml")
> File "E:\code\Edge-LBAM-main\MECNet\config.py", line 6, in **init**
> with open(config_path, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'
> Cuda is available!

We have provided the config.yml, you can use it for training,but note that you must use canny edge to train the model first,then use the edge of MECNet.

**Comment by song201216** [comment]
Thank you for your help.
