### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by naoki7090624** [wds1998/Edge-LBAM#6]
Thanks for sharing your great work!

When I run train.py, I got the following error.
```
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    main()
  File "train.py", line 107, in main
    for inputImgs, GT, masks,img_gray, edge, masks_over in (data_loader):
ValueError: not enough values to unpack (expected 6, got 4)
```
Since the number of return values in ```data/dataloader_canny.py``` was not enough, I changed your code to the following.
```
mask = 1 - mask
inputImage = groundTruth * mask
tmp = np.transpose(groundTruth, (1, 2, 0))
tmp = tmp.numpy()
tmp = rgb2gray(tmp)
edge = canny(tmp, sigma=1.5).astype(np.float32)
edge = torch.from_numpy(edge.reshape((1, 256, 256))).float()
maskover = torch.cat((inputImage, mask[0].view(1, self.cropSize[0], self.cropSize[1])), 0)

return inputImage, groundTruth, mask, tmp, edge, maskover
```
However, I got the following error.
```
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 12, 262, 262] to have 3 channels, but got 12 channels instead
```

I'm not sure if the return value of mask_over is correct. Please let me know how to solve this problem.

**Comment by jxbs** [comment]
Hello，have you solved the problem? I'm confused by the same problem.

**Comment by naoki7090624** [comment]
Hello, I have solved this problem, but I encouraged another problem.

Edge_model could be passed by changing mask_over to 1ch mask.
```
def __getitem__(self, index):
        img = Image.open(self.imageFiles[index])
        mask = Image.open(self.masks[randint(0, self.numOfMasks - 1)])

        groundTruth = self.ImgTrans(img.convert('RGB'))
        #groundTruth = self.ImgTrans(img)
        maskover = self.maskTrans(mask)
        mask = self.maskTrans(mask.convert('RGB'))
        
        # we add this threshhold to force the input mask to be binary 0,1 values
        # the threshhold value can be changeble, i think 0.5 is ok
        threshhold = 0.5
        ones = mask >= threshhold
        zeros = mask < threshhold

        mask.masked_fill_(ones, 1.0)
        mask.masked_fill_(zeros, 0.0)

        # here, we suggest that the white values(ones) denotes the area to be inpainted, 
        # and dark values(zeros) is the values remained. 
        # Therefore, we do a reverse step let mask = 1 - mask, the input = groundTruth * mask, :).
        mask = 1 - mask
        inputImage = groundTruth * mask
        tmp = np.transpose(groundTruth, (1, 2, 0))
        tmp = tmp.numpy()
        tmp = rgb2gray(tmp)
        edge = canny(tmp, sigma=1.5).astype(np.float32)
        edge = torch.from_numpy(edge.reshape((1, 256, 256))).float()
        inputImage = torch.cat((inputImage, mask[0].view(1, self.cropSize[0], self.cropSize[1])), 0)
        #maskover = torch.cat((inputImage, mask[0].view(1, self.cropSize[0], self.cropSize[1])), 0)

        return inputImage, groundTruth, mask, tmp, edge, maskover
```
But I got the error in ```G_loss.backward()```. I could not find the solution.
```
Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 4, 4]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by jxbs** [comment]
> 
oh my god! Now I got this error, too.

**Comment by jxbs** [comment]
> Hello, I have solved this problem, but I encouraged another problem.
> 
> Edge_model could be passed by changing mask_over to 1ch mask.
> 
> ```
> def __getitem__(self, index):
>         img = Image.open(self.imageFiles[index])
>         mask = Image.open(self.masks[randint(0, self.numOfMasks - 1)])
> 
>         groundTruth = self.ImgTrans(img.convert('RGB'))
>         #groundTruth = self.ImgTrans(img)
>         maskover = self.maskTrans(mask)
>         mask = self.maskTrans(mask.convert('RGB'))
>         
>         # we add this threshhold to force the input mask to be binary 0,1 values
>         # the threshhold value can be changeble, i think 0.5 is ok
>         threshhold = 0.5
>         ones = mask >= threshhold
>         zeros = mask < threshhold
> 
>         mask.masked_fill_(ones, 1.0)
>         mask.masked_fill_(zeros, 0.0)
> 
>         # here, we suggest that the white values(ones) denotes the area to be inpainted, 
>         # and dark values(zeros) is the values remained. 
>         # Therefore, we do a reverse step let mask = 1 - mask, the input = groundTruth * mask, :).
>         mask = 1 - mask
>         inputImage = groundTruth * mask
>         tmp = np.transpose(groundTruth, (1, 2, 0))
>         tmp = tmp.numpy()
>         tmp = rgb2gray(tmp)
>         edge = canny(tmp, sigma=1.5).astype(np.float32)
>         edge = torch.from_numpy(edge.reshape((1, 256, 256))).float()
>         inputImage = torch.cat((inputImage, mask[0].view(1, self.cropSize[0], self.cropSize[1])), 0)
>         #maskover = torch.cat((inputImage, mask[0].view(1, self.cropSize[0], self.cropSize[1])), 0)
> 
>         return inputImage, groundTruth, mask, tmp, edge, maskover
> ```
> 
> But I got the error in `G_loss.backward()`. I could not find the solution.
> 
> ```
> Variable._execution_engine.run_backward(
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 4, 4]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> ```

I have tried to set inplace=False in nn.ReLU and nn.LeakyReLU, but this error never be resolved.

**Comment by buloseshi** [comment]
> 

I got the same error,too! Jesus, do you find any solutions?
